name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "kt3k-deploy-test"
          entrypoint: "./main.ts" # TODO: update entrypoint
